apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: student-portal
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3500
      targetPort: 3500
      nodePort: 30500
