apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: student-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: la000la/student-portal-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
          env:
            - name: host
              value: mysql
            - name: user
              value: root
            - name: password
              value: mysql123
            - name: database
              value: school
